[default]
address = "0.0.0.0"

[debug]
port = 8000
log = "normal"

[release]
address = "127.0.0.1"
port = 8080
# workers = [number of cpus * 2]
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }